/*
 *   Project     : Balancing
 *   Filename    : Balancing.java
 *   Author      : Camarly Thomas <camarly@stu.ucc.edu.jm>
 *   Id.No.      : 20204241
 *   Course      : ITT
 *   Version     : 0.1
 *   Copyright   : All rights reserved 23 Nov 2021 19:13:46
 *   Description : 

 *   Function Name : 
 *   Purpose       : 
 *   Description   :

 */
package project;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static project.Reports.DBUrl;
import static project.Reports.DBpassword;
import static project.Reports.DBuser;
import static project.Reports.result;
import static project.Reports.statement;

/**
 *
 * @author Camarly Thomas <camarly@stu.ucc.edu.jm>
 */
public class Balancing extends javax.swing.JFrame {

    /**
     * Creates new form Balancing
     */
    LocalDate myDate = LocalDate.now();
    static Connection con = null;
    static Statement statement = null;
    static ResultSet result = null;

    static String DBUrl = "jdbc:mysql://localhost:3306/ThomasHardware";
    static String DBuser = "root";
    static String DBpassword = "root";

    

    DefaultTableModel tableModel;

    public Balancing() {
        initComponents();
        setDefaultCloseOperation(Balancing.DISPOSE_ON_CLOSE);
        dateField.setText(" " + myDate);
        JOptionPane.showMessageDialog(null, "Please enter the total from your cash register into the 'Cash Register Amount' field and then click the Balance button", "Balancing", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CashierField = new javax.swing.JTextField();
        ApplicationAMNTField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DailySalesTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        varianceTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        balButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CashierField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashierFieldActionPerformed(evt);
            }
        });

        ApplicationAMNTField.setEditable(false);

        DailySalesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(DailySalesTable);

        jLabel1.setText("Cash Register Amount");

        jLabel2.setText("Application Amount");

        dateField.setEditable(false);
        dateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Date");

        varianceTextField.setEditable(false);
        varianceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varianceTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Variance");

        balButton.setText("Balance");
        balButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 215, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(varianceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(169, 169, 169))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ApplicationAMNTField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CashierField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(balButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CashierField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ApplicationAMNTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(balButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(varianceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CashierFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashierFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CashierFieldActionPerformed

    private void dateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateFieldActionPerformed

    private void varianceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varianceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varianceTextFieldActionPerformed

    private void balButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balButtonActionPerformed


        if (CashierField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a valid amount in the Cashier Value Field", "Value Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                double cashierAMNT = Double.parseDouble(CashierField.getText());
//            double appAMNT = Double.parseDouble(ApplicationAMNTField.getText());

                double appAMNT = SQLscripts.getAppAMNT(myDate.toString());
                ApplicationAMNTField.setText(Double.toString(appAMNT));
                double variance = (cashierAMNT - appAMNT);
                

                if (variance > 1.00) {
//                    loadSales();
                    varianceTextField.setText(Double.toString(variance));
                    JOptionPane.showMessageDialog(null, "Check off values are off, revisit your figures and totals", "Balance Error", JOptionPane.ERROR_MESSAGE);
                } else {
//                    loadSales();
                    varianceTextField.setText(Double.toString(variance));
                    JOptionPane.showMessageDialog(null, "Daily Sales Closed", "Balancing Passed", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(Balancing.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_balButtonActionPerformed

    //loads the sales info into the table on the table.
    public void loadSales() {
        Connection con = null;
        try {
            con = Database.getConnection(DBUrl, DBuser, DBpassword);
            statement = con.createStatement();
            result = statement.executeQuery("SELECT * FROM Item");
//                itemTable.setModel((TableModel) result);

            String[] columns = {"ItemID", "Description", "TotalInStock", "UnitPurchasePrice", "UnitSalePrice", "UnderStockValue"};
//                
            while (result.next()) {
                String ItemID = result.getString("ItemID");
                String Description = result.getString("ItemDescription");
                int TotalInStock = result.getInt("TotalInStock");
                double PurchasePrice = result.getDouble("UnitPurchasePrice");
                double SalePrice = result.getDouble("UnitSalePrice");
                double UnderStockValue = result.getDouble("UnderStockValue");

                Object[] data = {ItemID, Description, TotalInStock, PurchasePrice, SalePrice, UnderStockValue};
                tableModel = (DefaultTableModel) DailySalesTable.getModel(); //testing table model;
                tableModel.insertRow(tableModel.getRowCount(), data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Balancing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Balancing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Balancing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Balancing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Balancing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApplicationAMNTField;
    private javax.swing.JTextField CashierField;
    private javax.swing.JTable DailySalesTable;
    private javax.swing.JButton balButton;
    private javax.swing.JTextField dateField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField varianceTextField;
    // End of variables declaration//GEN-END:variables
}
